### ISSUE TITLE
Presets translation

### ISSUE THREAD

**Issue by SeverineCornillon** [radima/RADIMA_JOSM#2]
1. Roads feature need to be translated as "Routes"
2. In Roads, Water and Land Use (Pastures, Forestry, Agriculture) features, translate "Hazards" category as "Risques", Quality as "Qualité", General Access as "Accès général", Livestock Wet/Dry season as "Elevage en saison sèche/humide" and Land Cover as "Couverture terrestre"
3. In Migration routes, translate Migration type values as "élevage, sauvage"
4. In Water, Forestry and Agriculture features, translate Access values to "traditionnel, public, privé, statutaire, inconnu"
5. In Pasture and Forestry features, translate Leaf types values as "feuilles, mixte, aiguilles"
6. In Pasture feature, translate Wetland types values as "herbacée, boisée, lit de roseaux, de marée"

**Comment by radima** [comment]
Fixed
