### ISSUE TITLE
Presets modifications

### ISSUE THREAD

**Issue by SeverineCornillon** [radima/RADIMA_JOSM#3]
1. Add "Horses" (FR="Chevaux") value in all livestock types (Animal crossing, Migration routes, Water and Land Use features)
2. Add "Warthog" (FR="Phacochère") value in all wildlife types (Animal crossing, Migration routes, Water and Land Use features)
3. Need to replace Operator values in Water features by "gestion coutumière, gouvernement, privé, inconnu, comité de gestion"
4. Replace "Trou de forage" feature name by "Forage" only
5. Remove "Trough" (FR="Abreuvoir") from the Presets and add it into the Water features attributes with values "yes, no" (FR="oui, non) + add a new attribute into the Water features called "Number of troughs" (FR="Nombre d'abreuvoirs")
6. Add "Desertification" (FR="Désertification") value in all the hazard types

**Comment by radima** [comment]
Fixed, apart from point 5 - troughs are present as independent features in Ngorongoro
Number of troughs attribute already exists
